{{- if .Values.enabled -}}
{{- if .Values.persistence.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ckan.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: sddi-ckan
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  serviceName: {{ .Chart.Name }}-hl
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ckan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.component }}
  template:
    metadata:
      labels:
        {{- include "ckan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.component }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/configmap-env: {{ include (print $.Template.BasePath "/ckan-configMap-env.yml") . | sha256sum }}
        checksum/secret-db: {{ include (print $.Template.BasePath "/ckan-sct-db.yml") . | sha256sum }}
        checksum/secret-smtp: {{ include (print $.Template.BasePath "/ckan-sct-smtp.yml") . | sha256sum }}
        checksum/secret-solr: {{ include (print $.Template.BasePath "/ckan-sct-solr.yml") . | sha256sum }}
        checksum/secret-session: {{ include (print $.Template.BasePath "/ckan-sct-session.yml") . | sha256sum }}
        checksum/secret-api-token: {{ include (print $.Template.BasePath "/ckan-sct-api-token.yml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ckan.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "ckan.fullname" . }}
        # Create emptyDir volumes to get directories with write permission in openShift
        {{ if .Values.openShift.enabled }}
        - name: srv-app-i18n
          emptyDir:
            sizeLimit: 500Mi
        - name: srv-app-data
          emptyDir:
            sizeLimit: 500Mi
        {{ end }}
        # Create licenses-volume for ckan licensesGroup configMap
        {{ if .Values.licensesConfigMap.enabled }}
        - name: licenses-volume
          configMap:
            name: {{ include "ckan.fullname" . }}-licenses
        {{ end }}
        # Create local-ini volume for ckan local-ini configMap
        {{ if .Values.localIni.enabled }}
        - name: local-ini
          configMap:
            name: ckan-local-ini
        {{ end }}
        # Create schema-volume for ckan-custom-schema configMap
        {{ if .Values.schemaConfigMap.enabled }}
        - name: schema-volume
          configMap:
            name: ckan-custom-schema
        {{ end }}


      initContainers:
      {{ if not .Values.openShift.enabled }}
      - name: init-data
        image: "{{ .Values.initContainers.initdata.image.repository }}:{{ .Values.initContainers.initdata.image.tag }}"
        command: ["sh", "-c", "chown -Rv 92:92 {{ .Values.persistence.storagePath }}"]
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.storagePath }}
          readOnly: false
      {{ end }}


      - name: pg-ready
        image: "{{ .Values.initContainers.pgready.image.repository }}:{{ .Values.initContainers.pgready.image.tag }}"
        command:
          - pg_isready
        env:
          - name: PGHOST
            value: {{ .Values.global.db.host | default .Values.db.host | quote }}
          - name: PGPORT
            value: {{ .Values.global.db.port | default .Values.db.port | quote }}
          - name: PGDATABASE
            value: {{ .Values.global.db.dbname | default .Values.db.dbname | quote }}
          - name: PGUSER
            value: {{ .Values.global.db.auth.username | default .Values.db.auth.username | quote }}
          - name: PGPASSWORD
            value: {{ .Values.global.db.auth.password | default .Values.db.auth.password | quote }}


      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "ckan.fullname" . }}-env
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-db
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-smtp
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-solr
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-session
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-api-token
            {{ if .Values.sysadmin.enabled }}
            - secretRef:
                name: {{ include "ckan.fullname" . }}-sct-sysadmin
            {{ end }}

          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.storagePath }}
            # Mount emptyDir volumes
            {{ if .Values.openShift.enabled }}
            - name: srv-app-data
              mountPath: /srv/app/data/
            - name: srv-app-i18n
              mountPath: /srv/app/src/ckan/ckan/public/base/i18n/
            {{ end }}
            # Mount licenses-volume
            {{ if .Values.licensesConfigMap.enabled }}
            - name: licenses-volume
              mountPath: /srv/app/licenses/
            {{ end }}
            # Mount local-ini volume
            {{ if .Values.localIni.enabled }}
            - name: local-ini
              mountPath: /srv/app/production.ini
              subPath: production.ini
            {{ end }}
            # Mount schema-volume
            {{ if .Values.schemaConfigMap.enabled }}
            - name: schema-volume
              mountPath: /srv/app/schema/
            {{ end }}

          startupProbe:
            httpGet:
              path: /api/3/action/status_show
              port: 5000
            initialDelaySeconds: {{ .Values.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.startup.periodSeconds }}
            failureThreshold: {{ .Values.startup.failureThreshold }}
            timeoutSeconds: {{ .Values.startup.timeoutSeconds }}

          readinessProbe:
            httpGet:
              path: /api/3/action/status_show
              port: 5000
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
            failureThreshold: {{ .Values.readiness.failureThreshold }}
            timeoutSeconds: {{ .Values.readiness.timeoutSeconds }}

          livenessProbe:
            httpGet:
              path: /api/3/action/status_show
              port: 5000
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
            failureThreshold: {{ .Values.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
{{- end -}}
